using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DiyetListesiOlusturmaProgrami.UI
{
    public enum FizikselAktiviteEnum
    {
        Yürüyüş,
        Koşu,
        BisikleteBinme,
        Yüzme,
        KoşuBandıKullanma,
        DansEtme,
        Yoga, 
        Pilates,
        AğırsikletAntrenmanı,
        KürekÇekme,
        FutbolOynamak,
        BasketbolOynamak,
        VoleybolOynamak,
        TenisOynamak,
        Golfoynamak,
        KaykayYapmak,
        SkiYapmak,
        KayaklaDağcılık,
        DağcılıkTırmanış,
        SörfYapmak,
        YelkenYapmak,
        AtBinmek,
        Zumba,
        Kickboks,
        Boks,
        MuayThai,
        BeyzbolOynamak,
        RugbyOynamak,
        AmerikanFutboluOynamak,
        KricketOynamak,
        JimnastikYapmak,
        HalterKaldırmak,
        CrossFit,
        SavaşSanatıJudo, Karate, Taekwondo, vb,
        ÇıkışHiking,
        DağBisikleti,
        ZıplamaIpiIleEgzersiz,
        KayakYapmak,
        SporSalonuEgzersizleri, Bodybuilding, kardiyo,
        Trekking,
        ParkurYapmak,
        Cimnastik,
        KuşaklıEğitmenlikAerobik, fitness,
        AçıkHavaKoşusu,
        Judo,
        Wushu,
        KungFu,
        SavaşSporları,
        SporTırmanışı,
        BungeeJumping,
        ParaşütleAtlama,
        Kano,
        Rafting,
        DağYürüyüşü,
        TempoluYürüyüş,
        FizikselTerapiEgzersizleri,
        BuzPateni,
        SığSudaEgzersiz,
        Plajvoleybolu,
    }
}
