using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DiyetListesiOlusturmaProgrami.UI
{
    public enum FizikselAktiviteEnum
    {
        Yok,
        Yürüyüş,
        Koşu,
        Bisiklet,
        Yüzme,
        KoşuBandı,
        Dans,
        Yoga, 
        Pilates,
        AğırsikletAntrenmanı,
        Kürek,
        Futbol,
        Basketbol,
        Voleybol,
        Tenis,
        Golf,
        Kaykay,
        Ski,
        Dağcılık,
        DağcılıkTırmanışı,
        Sörf,
        Yelken,
        AtBinmek,
        Zumba,
        Kickboks,
        Boks,
        MuayThai,
        Beyzbol,
        Rugby,
        AmerikanFutbolu,
        Kricket,
        Jimnastik,
        Halter,
        CrossFit,
        SavaşSanatıJudo, Karate, Taekwondo, vb,
        ÇıkışHiking,
        DağBisikleti,
        ZıplamaIpi,
        Kayak,
        Egzersizler, Bodybuilding, kardiyo,
        Trekking,
        Parkur,
        Cimnastik,
        KuşaklıEğitmenlikAerobik, fitness,
        Judo,
        Wushu,
        KungFu,
        SavaşSporları,
        SporTırmanışı,
        BungeeJumping,
        Paraşüt,
        Kano,
        Rafting,
        DağYürüyüşü,
        TempoluYürüyüş,
        FizikselTerapiEgzersizleri,
        BuzPateni,
        SığSudaEgzersiz,
        PlajVoleybolu,
    }
}
